name: 🎮 PSVita Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.x
  # warnings=no silences the signedness noise to speed up log processing
  SCONSFLAGS: verbose=yes warnings=no werror=no debug_symbols=no x11=no alsa=no pulseaudio=no CXXFLAGS="-Drestrict=__restrict"
  VITASDK: /usr/local/vitasdk
  EUID: 1 makepkg

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-vita
  cancel-in-progress: true

jobs:
  vita-template:
    runs-on: "ubuntu-24.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v4

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Cache VitaSDK
        id: cache-vitasdk
        uses: actions/cache@v3
        with:
          path: /usr/local/vitasdk
          key: ${{ runner.os }}-vitasdk-v1

      - name: Setup VitaSDK
        if: steps.cache-vitasdk.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install cmake libarchive-tools fakeroot zip libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev -y
          git clone https://github.com/vitasdk/vdpm
          git clone https://github.com/isage/vita-packages-extra
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh
          export PATH=$VITASDK/bin:$PATH
          vdpm vita-rss-libdl
          cd ../vita-packages-extra/pvr_psp2
          vita-makepkg
          vdpm *-arm.tar.xz

      - name: Add VitaSDK to PATH
        run: echo "/usr/local/vitasdk/bin" >> $GITHUB_PATH

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          # -j$(nproc) uses all available CPU cores to speed up the 50-minute build
          sconsflags: ${{ env.SCONSFLAGS }} -j2
          platform: vita
          target: release
          tools: false

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: vita-template
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
